name: Build IPA

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: actions/checkout@master
      - uses: sinoru/actions-setup-xcode@v2
        with:
          xcode-version: '13.4' # Exact version of a Xcode version to use
          apple-id: 'andrped94@gmail.com' # Apple ID to download from Apple Developer when Xcode not available in local
          apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
      - run: fastlane scan

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.4'
      - run: flutter pub get
      - run: flutter build ios --release
      #- run: flutter build ipa --release

      - uses: actions/upload-artifact@v2
        with:
          name: release-ipa
          path: build/app/outputs/ipa/release/app-release.ipa
          if-no-files-found: error
