name: Build and upload APK (Android) mobile app

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.4'
      - run: flutter pub get
      - run: flutter build apk --release

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: debug-apk
          path: build/app/outputs/apk/release/app-release.apk
